<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileMonitoring.Infrastructure\FileMonitoring.Infrastructure.csproj" />
  </ItemGroup>

</Project>
